# Generated by Django 4.2.3 on 2023-08-13 16:14

from django.db import migrations, models
import subtitlingAI.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitlingAI', '0003_alter_videofile_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish')], default='EN', max_length=5),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_file',
            field=models.FileField(upload_to='uploaded/', validators=[subtitlingAI.validators.validate_file_extension]),
        ),
    ]
