# Generated by Django 4.2.3 on 2023-08-13 17:13

from django.db import migrations, models
import subtitlingAI.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitlingAI', '0004_videofile_language_alter_videofile_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='project_id',
            field=models.CharField(default='test_project_id', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_file',
            field=models.FileField(upload_to='uploaded/<django.db.models.fields.CharField>/', validators=[subtitlingAI.validators.validate_file_extension]),
        ),
    ]
