# Generated by Django 4.2.3 on 2023-08-13 21:28

from django.db import migrations, models
import subtitlingAI.models
import subtitlingAI.validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitlingAI', '0005_videofile_project_id_alter_videofile_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofile',
            old_name='language',
            new_name='transcription_language',
        ),
        migrations.AlterField(
            model_name='videofile',
            name='project_id',
            field=models.CharField(default='158846036087', max_length=100, validators=[subtitlingAI.validators.validate_google_project_id]),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='video_file',
            field=models.FileField(upload_to=subtitlingAI.models.VideoFile.get_upload_path, validators=[subtitlingAI.validators.validate_file_extension]),
        ),
    ]
